// angular-project/MyEmployeeUI/src/app/components/calc/calc.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-calc',
  templateUrl: './calc.component.html',
  styleUrls: ['./calc.component.css']
})
export class CalcComponent implements OnInit {
  x:number=20;
  y:number=10;

  result:number;
  constructor() { }

  ngOnInit(): void {
  }

  calc(op:string){
    switch(op){
      case 'add':
        this.result=this.x+this.y;
        break;
      case 'sub':
        this.result=this.x-this.y;
        break;
    }
  }

}


<p>x={{x}}</p>
<p>y={{y}}</p>

<button (click)="calc('add')">ADD</button>
<button (click)="calc('sub')">SUB</button>
<button (click)="calc('mul')">MUL</button>
<button (click)="calc('div')">DIV</button>
<br />
<div *ngIf="result">Result is: {{result}}</div>

// react-app/src/components/Calc.js
import { Component } from "react";

export class Calc extends Component{
    
  spanStyle={
    fontSize: 18
  }
  constructor(props){
        super(props);

        this.state={
          x: 10,
          y: 5,
          ans: 0
        }
  }
  render(){
    return(
      <div>
        <h1>Calc Ops</h1>
        <p>x= {this.state.x}</p>
        <p>y= {this.state.y}</p>
        <span className="span-style">Ans is: {this.state.ans === 0? '': this.state.ans}</span>
        <hr />
        <button onClick={()=>{
            this.calc('ADD');
        }}>ADD</button>
        <button onClick={()=>{
          this.calc('SUB');
        }}>SUB</button>
        <button onClick={()=>{
          this.calc('DIV');
        }}>DIV</button>
        <button onClick={()=>{
          this.calc('MUL');
        }}>MUL</button>
      </div>
    )
  }

  calc(op){
    console.log(op);
    switch(op){
      case 'ADD':
        this.setState({
          ans: this.state.x + this.state.y
        })
        break;
      case 'SUB':
        this.setState({
          ans: this.state.x - this.state.y
        })
        break;
      case 'MUL':
        this.setState({
          ans: this.state.x * this.state.y
        })
        break;
      case 'DIV':
        this.setState({
          ans: this.state.x / this.state.y
        })
        break;
      default:

    }
  }
}
